#!/bin/sh

set -e

[ -f /etc/sysconfig/grafana-de-server ] && . /etc/sysconfig/grafana-de-server

startGrafana() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start grafana-de-server.service
	elif [ -x /etc/init.d/grafana-de-server ] ; then
		/etc/init.d/grafana-de-server start
	elif [ -x /etc/rc.d/init.d/grafana-de-server ] ; then
		/etc/rc.d/init.d/grafana-de-server start
	fi
}

stopGrafana() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop grafana-de-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/grafana-de-service ] ; then
		/etc/init.d/grafana-de-service stop
	elif [ -x /etc/rc.d/init.d/grafana-de-service ] ; then
		/etc/rc.d/init.d/grafana-de-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$GRAFANA_USER" ] && GRAFANA_USER="grafana"
	[ -z "$GRAFANA_GROUP" ] && GRAFANA_GROUP="grafana"
	if ! getent group "$GRAFANA_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$GRAFANA_GROUP"
	fi
	if ! getent passwd "$GRAFANA_USER" > /dev/null 2>&1 ; then
    useradd -r -g grafana -d /usr/share/grafana-de -s /sbin/nologin \
    -c "grafana user" grafana
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafana-de/conf/sample.ini $CONF_FILE
    cp /usr/share/grafana-de/conf/ldap.toml /etc/grafana-de/ldap.toml
  fi

  if [ ! -f $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafana-de/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafana-de/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

 	# Set user permissions on /var/log/grafana-de, /var/lib/grafana-de
	mkdir -p /var/log/grafana-de /var/lib/grafana-de
	chown -R $GRAFANA_USER:$GRAFANA_GROUP /var/log/grafana-de /var/lib/grafana-de
	chmod 755 /var/log/grafana-de /var/lib/grafana-de

	# configuration files should not be modifiable by grafana user, as this can be a security issue
	chown -Rh root:$GRAFANA_GROUP /etc/grafana-de/*
	chmod 755 /etc/grafana-de
	find /etc/grafana-de -type f -exec chmod 640 {} ';'
	find /etc/grafana-de -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable grafana-de-server.service"
    echo "### You can start grafana-de-server by executing"
    echo " sudo /bin/systemctl start grafana-de-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting grafana-de-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add grafana-de-server"
    echo "### In order to start grafana-de-server, execute"
    echo " sudo service grafana-de-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopGrafana
    startGrafana
  fi
fi
