#!/bin/sh

set -e

echo "POSTTRANS: Running script"

[ -f /etc/sysconfig/grafana-de-server ] && . /etc/sysconfig/grafana-de-server

# copy config files if missing
if [ ! -f /etc/grafana-de/grafana.ini ]; then
  echo "POSTTRANS: Config file not found"

  if [ -f /etc/grafana-de/grafana.ini.rpmsave ]; then
    echo "POSTTRANS: /etc/grafana-de/grafana.ini.rpmsave config file found."
    mv /etc/grafana-de/grafana.ini.rpmsave /etc/grafana-de/grafana.ini
    echo "POSTTRANS: /etc/grafana-de/grafana.ini restored"

    if [ -f /etc/grafana-de/ldap.toml.rpmsave ]; then
      echo "POSTTRANS: /etc/grafana-de/ldap.toml.rpmsave found"
      mv /etc/grafana-de/ldap.toml.rpmsave /etc/grafana-de/ldap.toml
      echo "POSTTRANS: /etc/grafana-de/ldap.toml restored"
    fi

    echo "POSTTRANS: Restoring config file permissions"
    chown -Rh root:$GRAFANA_GROUP /etc/grafana-de/*
    chmod 755 /etc/grafana-de
    find /etc/grafana-de -type f -exec chmod 640 {} ';'
    find /etc/grafana-de -type d -exec chmod 755 {} ';'
  fi
fi


